services:
  church-lite:
    image: church-lite
    container_name: service_church-lite_frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_TOKEN: ${GIT_TOKEN}
    environment:
      NODE_ENV: production
    ports:
      - 5051:80
